/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    articles: Article;
    guides: Guide;
    tools: Tool;
    media: Media;
    testimonials: Testimonial;
    pressMentions: PressMention;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    pressMentions: PressMentionsSelect<false> | PressMentionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar')
    | ('en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar')[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown in the CMS
   */
  name: string;
  /**
   * Admin: full access. Editor: can create/edit content. Viewer: read-only.
   */
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Long-form journal articles and story pieces. Localized across 9 languages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL slug, lowercase, hyphen-separated. Not localized.
   */
  slug: string;
  category?: ('story' | 'guide' | 'product' | 'press' | 'journal') | null;
  /**
   * 1-3 sentence summary shown at top of article.
   */
  tldr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Key takeaways shown as a bulleted list.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  pullQuotes?:
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Uploads (images, video, PDF). Cloud storage plugin rewrites to Supabase S3-compat bucket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO. Required.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer / source credit (optional).
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Per-country shipping & customs guides. Matches storefront /guides/[country] pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  country: 'us' | 'uk' | 'de' | 'fr' | 'au' | 'sg' | 'ca' | 'hk' | 'ar';
  title: string;
  /**
   * Example: '5-9 business days' or '3-5 日'
   */
  shippingDays: string;
  /**
   * Import duties, prohibited items, etc.
   */
  customsNotes?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Metadata for utility tools (shelf-life calculator, miso finder, etc.). Powers /tools/[slug] pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  /**
   * URL slug (e.g. 'shelf-life', 'miso-finder').
   */
  slug: string;
  title: string;
  /**
   * Short description shown in tool grid.
   */
  description: string;
  /**
   * Lucide icon name (e.g. 'Clock', 'Soup') OR emoji, depending on storefront rendering choice.
   */
  icon?: string | null;
  /**
   * Sort order in tool grid (lower = first).
   */
  order?: number | null;
  /**
   * Optional long-form explanation shown below the tool widget.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer testimonials shown on homepage and product pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Customer display name (e.g. 'Emma R.').
   */
  author: string;
  /**
   * Country label (e.g. 'United States', '日本').
   */
  country?: string | null;
  product?: {
    /**
     * Optional relationship to a story/product article. Leave blank if using free text.
     */
    linkedArticle?: (number | null) | Article;
    /**
     * Free-text product label if not linked to an article (e.g. 'Uji Sencha 50g').
     */
    freeText?: string | null;
  };
  rating: number;
  quote: string;
  /**
   * Verified purchaser badge.
   */
  verified?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Date of purchase (for recency sorting).
   */
  orderDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Press / media mentions. Logos shown in homepage press strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pressMentions".
 */
export interface PressMention {
  id: number;
  /**
   * Publication name (e.g. 'Monocle', 'Kinfolk').
   */
  name: string;
  /**
   * Monochrome SVG logo preferred.
   */
  logoSvg?: (number | null) | Media;
  /**
   * Link to the article or feature.
   */
  url?: string | null;
  /**
   * Pull quote from the article (optional).
   */
  quote?: string | null;
  date?: string | null;
  /**
   * Display order in press strip.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pressMentions';
        value: number | PressMention;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  tldr?: T;
  heroImage?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pullQuotes?:
    | T
    | {
        quote?: T;
        attribution?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  country?: T;
  title?: T;
  shippingDays?: T;
  customsNotes?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  country?: T;
  product?:
    | T
    | {
        linkedArticle?: T;
        freeText?: T;
      };
  rating?: T;
  quote?: T;
  verified?: T;
  avatar?: T;
  orderDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pressMentions_select".
 */
export interface PressMentionsSelect<T extends boolean = true> {
  name?: T;
  logoSvg?: T;
  url?: T;
  quote?: T;
  date?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site-wide settings: announcement bar, social links, footer copy, hero defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Background video URL for the homepage CinematicHero. Upload to Media collection first, then paste the URL here. Prefer MP4 <10MB. If empty, uses the env-driven fallback (NEXT_PUBLIC_HERO_VIDEO_URL) or a gradient-only hero.
   */
  heroVideoUrl?: string | null;
  /**
   * Static image shown while the hero video buffers (or as a still on mobile / reduced-motion). Should match the video's first frame for a clean fade-in.
   */
  heroPosterUrl?: string | null;
  /**
   * Fallback hero image URL (used if no video set).
   */
  heroImageUrl?: string | null;
  heroCopy?: {
    /**
     * Small all-caps kicker. Default: 'Drop No. 01 — Limited release'.
     */
    eyebrow?: string | null;
    /**
     * Top line of the giant H1. Default: 'Rescued Japanese'.
     */
    headlineLine1?: string | null;
    /**
     * Bottom line of the giant H1. Default: 'craft food,'.
     */
    headlineLine2?: string | null;
    /**
     * Lines that cycle through the typewriter effect. Order matters. Empty = uses defaults. Each line localised.
     */
    typewriterStrings?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Sub-paragraph below the headline. Default: 'Each drop is a single curated bundle...'.
     */
    body?: string | null;
    /**
     * Small caps meta strip. Default: 'Kyoto, Japan' / 'EMS worldwide' / '50 units'.
     */
    metaLines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Primary button label. Default: 'Shop the drop'.
     */
    primaryCtaLabel?: string | null;
    /**
     * Primary button destination. Default: '/products'.
     */
    primaryCtaUrl?: string | null;
    /**
     * Secondary link label. Default: 'Our story'.
     */
    secondaryCtaLabel?: string | null;
    /**
     * Secondary link destination. Default: '/#story'.
     */
    secondaryCtaUrl?: string | null;
  };
  announcementBar?: {
    /**
     * Master switch. Uncheck to hide the marquee bar entirely.
     */
    enabled?: boolean | null;
    /**
     * Phrases that scroll across the top of every page. Drag to reorder. 4–8 items work best (too few → repetition obvious, too many → marquee speed drops). Each phrase localised across all 10 languages.
     */
    items?:
      | {
          text: string;
          /**
           * Optional URL. If empty, the phrase is plain text.
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * (Legacy) Single phrase. Only used if `items` array is empty. Kept for backward compatibility.
     */
    text?: string | null;
    link?: string | null;
    /**
     * CSS color value (hex/rgb/oklch). Default: Sericia ink.
     */
    backgroundColor?: string | null;
    /**
     * CSS color value. Default: Sericia paper.
     */
    textColor?: string | null;
    /**
     * Full marquee cycle time. Lower = faster. Default 40s.
     */
    scrollSpeedSeconds?: number | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'x' | 'tiktok' | 'youtube' | 'pinterest' | 'facebook' | 'line' | 'wechat' | 'threads';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCopy?: {
    tagline?: string | null;
    copyrightText?: string | null;
    /**
     * Footer top band — small eyebrow. Default: 'Quietly, from Kyoto'.
     */
    editorialEyebrow?: string | null;
    /**
     * Footer top band — large heading. Default: 'Four to six times a year, we open the door.'.
     */
    editorialHeading?: string | null;
    /**
     * Subscribe-band body copy. Default mentions Kyoto, EMS, 48h.
     */
    editorialBody?: string | null;
    /**
     * Small print under subscribe form. Default mentions monthly, unsubscribe, privacy.
     */
    subscribePrivacyNote?: string | null;
    /**
     * Footer band 3 — Studio paragraph. Default: 'Paradigm LLC — registered in Delaware...'.
     */
    studioCopy?: string | null;
    /**
     * Locale-acknowledgement label. Default: 'Currently viewing:'.
     */
    currentlyViewingLabel?: string | null;
    /**
     * Footer link columns. Drag to reorder. 4 columns is the visual sweet spot. If empty, defaults to coded structure (Shop / Tools / Company / Support).
     */
    columns?:
      | {
          /**
           * Column heading (eyebrow style).
           */
          title: string;
          links?:
            | {
                label: string;
                url: string;
                /**
                 * Tick if URL opens in new tab.
                 */
                external?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Sticky launch promotion strip above the header. Editor controls enabled/copy/code without a deploy. Code must match the actual Medusa promotion to be applied at checkout.
   */
  couponBanner?: {
    /**
     * Master switch — uncheck to hide entirely.
     */
    enabled?: boolean | null;
    /**
     * Coupon code. Should match a Medusa promotion exactly. This same value is used as the link to the checkout pre-applied path.
     */
    code?: string | null;
    /**
     * Top label. Default: 'Launch offer'. Localised so 'ローンチ特典' shows for ja viewers.
     */
    headline?: string | null;
    /**
     * Main offer phrase. Default: '10% off your first order'. Reads after the headline + dash.
     */
    offerText?: string | null;
    /**
     * Glue text before the code. Default: 'with code'.
     */
    withCodePrefix?: string | null;
    /**
     * Bump this string (v2/v3/...) to force every visitor to see the banner again. We append it to the localStorage dismiss key.
     */
    storageKeyVersion?: string | null;
  };
  /**
   * Header navigation items. If empty, falls back to the coded brand defaults (Shop / Current drop / Story / Guides). Localised per item.
   */
  navigation?: {
    items?:
      | {
          label: string;
          url: string;
          /**
           * Render with stronger visual weight (e.g. CTA-style).
           */
          highlighted?: boolean | null;
          mega?: {
            enabled?: boolean | null;
            columns?:
              | {
                  title?: string | null;
                  links?:
                    | {
                        label: string;
                        url: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            featuredCards?:
              | {
                  title: string;
                  caption?: string | null;
                  url: string;
                  imageUrl?: string | null;
                  tone?:
                    | (
                        | 'paper'
                        | 'tea'
                        | 'miso'
                        | 'mushroom'
                        | 'seasoning'
                        | 'drop'
                        | 'ink'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Region-specific banner shown under the header. Country code matches Sericia's region slugs (jp/us/eu/gb/ca/au/sg/hk/me). First match wins. Empty array → no banner.
   */
  regionBanners?:
    | {
        regionCode: 'jp' | 'us' | 'eu' | 'gb' | 'ca' | 'au' | 'sg' | 'hk' | 'me';
        /**
         * Banner copy. e.g. 'Free shipping over $200' or '送料無料 ¥30,000〜'.
         */
        text: string;
        /**
         * Optional link. If empty, banner is plain text.
         */
        url?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Edit every section eyebrow / heading / intro on the homepage. Each field is localised. Empty fields fall back to the coded brand default — never ship empty strings.
   */
  homepageCopy?: {
    currentDrop?: {
      eyebrow?: string | null;
      title?: string | null;
      lede?: string | null;
    };
    featuredBundle?: {
      eyebrow?: string | null;
      heroVideoUrl?: string | null;
      heroPosterUrl?: string | null;
      secondaryVideoUrlA?: string | null;
      secondaryPosterUrlA?: string | null;
      secondaryVideoUrlB?: string | null;
      secondaryPosterUrlB?: string | null;
    };
    interstitial?: {
      videoUrl?: string | null;
      posterUrl?: string | null;
      caption?: string | null;
    };
    mostLoved?: {
      eyebrow?: string | null;
      title?: string | null;
    };
    makers?: {
      eyebrow?: string | null;
      title?: string | null;
      lede?: string | null;
      /**
       * Producer cards. If empty, defaults to coded 3-maker fallback (Yamane-en / Kurashige Jozoten / Yamagata Mori).
       */
      items?:
        | {
            name: string;
            craft: string;
            region: string;
            note: string;
            videoUrl?: string | null;
            posterUrl?: string | null;
            tone?: ('tea' | 'miso' | 'mushroom' | 'seasoning' | 'paper' | 'ink') | null;
            id?: string | null;
          }[]
        | null;
    };
    philosophy?: {
      eyebrow?: string | null;
      body?: string | null;
    };
    waitlist?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
      footnote?: string | null;
    };
    howItWorks?: {
      eyebrow?: string | null;
      title?: string | null;
      /**
       * 4 steps recommended. Defaults to coded 4-step fallback.
       */
      steps?:
        | {
            /**
             * e.g. '01' / '02'.
             */
            number: string;
            title: string;
            body: string;
            id?: string | null;
          }[]
        | null;
    };
    faq?: {
      eyebrow?: string | null;
      title?: string | null;
      /**
       * FAQ items. Defaults to coded 4-item brand baseline.
       */
      items?:
        | {
            q: string;
            a: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Button label below FAQ. Default: 'Read the full shipping policy'.
       */
      ctaLabel?: string | null;
      /**
       * Default: /shipping.
       */
      ctaUrl?: string | null;
    };
  };
  contact?: {
    supportEmail?: string | null;
    pressEmail?: string | null;
    phone?: string | null;
    addressLines?: string | null;
  };
  seoDefaults?: {
    defaultTitle?: string | null;
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage block composition. Drag-and-drop blocks in any order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Button label (e.g. 'Shop now').
             */
            ctaLabel?: string | null;
            /**
             * Destination URL or internal path.
             */
            ctaUrl?: string | null;
            /**
             * Background video or fallback image. Prefer MP4/WebM <10MB.
             */
            videoMedia?: (number | null) | Media;
            /**
             * Static image shown on mobile or if video fails.
             */
            fallbackImage?: (number | null) | Media;
            align?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * E.g. 'DROP 07' or '2026-春'.
             */
            dropNumber: string;
            title: string;
            description?: string | null;
            /**
             * Medusa product handle (e.g. 'sencha-uji-50g') — links to storefront /products/<handle>.
             */
            productHandle: string;
            countdownTo?: string | null;
            media?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'drop';
          }
        | {
            heading?: string | null;
            /**
             * Pick testimonials to feature here. Leave empty to auto-pull latest verified.
             */
            items?: (number | Testimonial)[] | null;
            /**
             * Max testimonials to show when auto-pulling.
             */
            limit?: number | null;
            layout?: ('carousel' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsStrip';
          }
        | {
            /**
             * Optional heading (e.g. 'As seen in').
             */
            heading?: string | null;
            items?: (number | PressMention)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pressStrip';
          }
        | {
            /**
             * Small kicker above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Image shown to the right of the text on desktop.
             */
            imageRight?: (number | null) | Media;
            imageLayout?: ('right' | 'left' | 'below') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            heading: string;
            subheading?: string | null;
            ctaLabel: string;
            /**
             * Small text below form (e.g. GDPR consent line).
             */
            disclaimer?: string | null;
            /**
             * Optional incentive text (e.g. '15% off first order' / 'Free shipping guide').
             */
            incentive?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroVideoUrl?: T;
  heroPosterUrl?: T;
  heroImageUrl?: T;
  heroCopy?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        typewriterStrings?:
          | T
          | {
              text?: T;
              id?: T;
            };
        body?: T;
        metaLines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaUrl?: T;
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        items?:
          | T
          | {
              text?: T;
              link?: T;
              id?: T;
            };
        text?: T;
        link?: T;
        backgroundColor?: T;
        textColor?: T;
        scrollSpeedSeconds?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerCopy?:
    | T
    | {
        tagline?: T;
        copyrightText?: T;
        editorialEyebrow?: T;
        editorialHeading?: T;
        editorialBody?: T;
        subscribePrivacyNote?: T;
        studioCopy?: T;
        currentlyViewingLabel?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    external?: T;
                    id?: T;
                  };
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  couponBanner?:
    | T
    | {
        enabled?: T;
        code?: T;
        headline?: T;
        offerText?: T;
        withCodePrefix?: T;
        storageKeyVersion?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              url?: T;
              highlighted?: T;
              mega?:
                | T
                | {
                    enabled?: T;
                    columns?:
                      | T
                      | {
                          title?: T;
                          links?:
                            | T
                            | {
                                label?: T;
                                url?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    featuredCards?:
                      | T
                      | {
                          title?: T;
                          caption?: T;
                          url?: T;
                          imageUrl?: T;
                          tone?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  regionBanners?:
    | T
    | {
        regionCode?: T;
        text?: T;
        url?: T;
        enabled?: T;
        id?: T;
      };
  homepageCopy?:
    | T
    | {
        currentDrop?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        featuredBundle?:
          | T
          | {
              eyebrow?: T;
              heroVideoUrl?: T;
              heroPosterUrl?: T;
              secondaryVideoUrlA?: T;
              secondaryPosterUrlA?: T;
              secondaryVideoUrlB?: T;
              secondaryPosterUrlB?: T;
            };
        interstitial?:
          | T
          | {
              videoUrl?: T;
              posterUrl?: T;
              caption?: T;
            };
        mostLoved?:
          | T
          | {
              eyebrow?: T;
              title?: T;
            };
        makers?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              items?:
                | T
                | {
                    name?: T;
                    craft?: T;
                    region?: T;
                    note?: T;
                    videoUrl?: T;
                    posterUrl?: T;
                    tone?: T;
                    id?: T;
                  };
            };
        philosophy?:
          | T
          | {
              eyebrow?: T;
              body?: T;
            };
        waitlist?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              footnote?: T;
            };
        howItWorks?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    q?: T;
                    a?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
            };
      };
  contact?:
    | T
    | {
        supportEmail?: T;
        pressEmail?: T;
        phone?: T;
        addressLines?: T;
      };
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              videoMedia?: T;
              fallbackImage?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        drop?:
          | T
          | {
              dropNumber?: T;
              title?: T;
              description?: T;
              productHandle?: T;
              countdownTo?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsStrip?:
          | T
          | {
              heading?: T;
              items?: T;
              limit?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        pressStrip?:
          | T
          | {
              heading?: T;
              items?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              imageRight?: T;
              imageLayout?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              disclaimer?: T;
              incentive?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}