/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    articles: Article;
    guides: Guide;
    tools: Tool;
    media: Media;
    testimonials: Testimonial;
    pressMentions: PressMention;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    pressMentions: PressMentionsSelect<false> | PressMentionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar')
    | ('en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar')[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'en' | 'ja' | 'de' | 'fr' | 'es' | 'it' | 'ko' | 'zh-TW' | 'ru' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown in the CMS
   */
  name: string;
  /**
   * Admin: full access. Editor: can create/edit content. Viewer: read-only.
   */
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Long-form journal articles and story pieces. Localized across 9 languages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL slug, lowercase, hyphen-separated. Not localized.
   */
  slug: string;
  category?: ('story' | 'guide' | 'product' | 'press' | 'journal') | null;
  /**
   * 1-3 sentence summary shown at top of article.
   */
  tldr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Key takeaways shown as a bulleted list.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  pullQuotes?:
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Uploads (images, video, PDF). Cloud storage plugin rewrites to Supabase S3-compat bucket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO. Required.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer / source credit (optional).
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Per-country shipping & customs guides. Matches storefront /guides/[country] pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  country: 'us' | 'uk' | 'de' | 'fr' | 'au' | 'sg' | 'ca' | 'hk' | 'ar';
  title: string;
  /**
   * Example: '5-9 business days' or '3-5 日'
   */
  shippingDays: string;
  /**
   * Import duties, prohibited items, etc.
   */
  customsNotes?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Metadata for utility tools (shelf-life calculator, miso finder, etc.). Powers /tools/[slug] pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  /**
   * URL slug (e.g. 'shelf-life', 'miso-finder').
   */
  slug: string;
  title: string;
  /**
   * Short description shown in tool grid.
   */
  description: string;
  /**
   * Lucide icon name (e.g. 'Clock', 'Soup') OR emoji, depending on storefront rendering choice.
   */
  icon?: string | null;
  /**
   * Sort order in tool grid (lower = first).
   */
  order?: number | null;
  /**
   * Optional long-form explanation shown below the tool widget.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer testimonials shown on homepage and product pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Customer display name (e.g. 'Emma R.').
   */
  author: string;
  /**
   * Country label (e.g. 'United States', '日本').
   */
  country?: string | null;
  product?: {
    /**
     * Optional relationship to a story/product article. Leave blank if using free text.
     */
    linkedArticle?: (number | null) | Article;
    /**
     * Free-text product label if not linked to an article (e.g. 'Uji Sencha 50g').
     */
    freeText?: string | null;
  };
  rating: number;
  quote: string;
  /**
   * Verified purchaser badge.
   */
  verified?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Date of purchase (for recency sorting).
   */
  orderDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Press / media mentions. Logos shown in homepage press strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pressMentions".
 */
export interface PressMention {
  id: number;
  /**
   * Publication name (e.g. 'Monocle', 'Kinfolk').
   */
  name: string;
  /**
   * Monochrome SVG logo preferred.
   */
  logoSvg?: (number | null) | Media;
  /**
   * Link to the article or feature.
   */
  url?: string | null;
  /**
   * Pull quote from the article (optional).
   */
  quote?: string | null;
  date?: string | null;
  /**
   * Display order in press strip.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pressMentions';
        value: number | PressMention;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  tldr?: T;
  heroImage?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pullQuotes?:
    | T
    | {
        quote?: T;
        attribution?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  country?: T;
  title?: T;
  shippingDays?: T;
  customsNotes?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  country?: T;
  product?:
    | T
    | {
        linkedArticle?: T;
        freeText?: T;
      };
  rating?: T;
  quote?: T;
  verified?: T;
  avatar?: T;
  orderDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pressMentions_select".
 */
export interface PressMentionsSelect<T extends boolean = true> {
  name?: T;
  logoSvg?: T;
  url?: T;
  quote?: T;
  date?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site-wide settings: announcement bar, social links, footer copy, hero defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Fallback hero video URL (if homepage hero block has no videoMedia).
   */
  heroVideoUrl?: string | null;
  /**
   * Fallback hero image URL.
   */
  heroImageUrl?: string | null;
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
    /**
     * CSS color value (hex/rgb/oklch).
     */
    backgroundColor?: string | null;
    textColor?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'x' | 'tiktok' | 'youtube' | 'pinterest' | 'facebook' | 'line' | 'wechat' | 'threads';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCopy?: {
    tagline?: string | null;
    copyrightText?: string | null;
    legalLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    supportEmail?: string | null;
    pressEmail?: string | null;
    phone?: string | null;
    addressLines?: string | null;
  };
  seoDefaults?: {
    defaultTitle?: string | null;
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage block composition. Drag-and-drop blocks in any order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Button label (e.g. 'Shop now').
             */
            ctaLabel?: string | null;
            /**
             * Destination URL or internal path.
             */
            ctaUrl?: string | null;
            /**
             * Background video or fallback image. Prefer MP4/WebM <10MB.
             */
            videoMedia?: (number | null) | Media;
            /**
             * Static image shown on mobile or if video fails.
             */
            fallbackImage?: (number | null) | Media;
            align?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * E.g. 'DROP 07' or '2026-春'.
             */
            dropNumber: string;
            title: string;
            description?: string | null;
            /**
             * Medusa product handle (e.g. 'sencha-uji-50g') — links to storefront /products/<handle>.
             */
            productHandle: string;
            countdownTo?: string | null;
            media?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'drop';
          }
        | {
            heading?: string | null;
            /**
             * Pick testimonials to feature here. Leave empty to auto-pull latest verified.
             */
            items?: (number | Testimonial)[] | null;
            /**
             * Max testimonials to show when auto-pulling.
             */
            limit?: number | null;
            layout?: ('carousel' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsStrip';
          }
        | {
            /**
             * Optional heading (e.g. 'As seen in').
             */
            heading?: string | null;
            items?: (number | PressMention)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pressStrip';
          }
        | {
            /**
             * Small kicker above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Image shown to the right of the text on desktop.
             */
            imageRight?: (number | null) | Media;
            imageLayout?: ('right' | 'left' | 'below') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            heading: string;
            subheading?: string | null;
            ctaLabel: string;
            /**
             * Small text below form (e.g. GDPR consent line).
             */
            disclaimer?: string | null;
            /**
             * Optional incentive text (e.g. '15% off first order' / 'Free shipping guide').
             */
            incentive?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroVideoUrl?: T;
  heroImageUrl?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        backgroundColor?: T;
        textColor?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerCopy?:
    | T
    | {
        tagline?: T;
        copyrightText?: T;
        legalLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        supportEmail?: T;
        pressEmail?: T;
        phone?: T;
        addressLines?: T;
      };
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              videoMedia?: T;
              fallbackImage?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        drop?:
          | T
          | {
              dropNumber?: T;
              title?: T;
              description?: T;
              productHandle?: T;
              countdownTo?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsStrip?:
          | T
          | {
              heading?: T;
              items?: T;
              limit?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        pressStrip?:
          | T
          | {
              heading?: T;
              items?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              imageRight?: T;
              imageLayout?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              disclaimer?: T;
              incentive?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}